name: Hourly (Permission)

on:
  schedule:
    - cron: "45 * * * 5"

permissions:
  actions: write
  contents: write

jobs:
  tag-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Commit and push changes
        run: |
          NOW=$(date +%s)
          TAG="hourly-permission-$NOW"
          git tag "$TAG"
          git push --atomic origin main "$TAG"
